### ISSUE TITLE
How / why is this different ?

### ISSUE THREAD

**Issue by dceejay** [alessh/node-red-contrib-email-out#1]
Hi, thanks for this node... but can you make it clear in the readme how and why this is different from the standard email node ?  Why would you use this one ? Why not enhance the existing one ? Thanks

**Comment by alessh** [comment]
Hi, 

I need an email node that outputs the original payload instead of mail body. Output the original payload enable me to do more things if sent successful.

To enhance the existing one i need to break compatibility.

Thanks.
